"""empty message

Revision ID: 2e977bcab9db
Revises: 7eeb36542b83
Create Date: 2021-10-29 15:09:51.425475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e977bcab9db'
down_revision = '7eeb36542b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eds', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('eds', 'revision_date')
    op.drop_constraint(None, 'TPIA_AEupdate', type_='foreignkey')
    op.create_foreign_key(None, 'TPIA_AEupdate', 'eds', ['eds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TPIA_AEupdate', type_='foreignkey')
    op.create_foreign_key(None, 'TPIA_AEupdate', 'users', ['eds_id'], ['id'])
    op.add_column('eds', sa.Column('revision_date', sa.VARCHAR(length=80), nullable=True))
    op.alter_column('eds', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
