"""empty message

Revision ID: a94740ee0ed4
Revises: b106403bf674
Create Date: 2021-09-27 16:53:40.706791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94740ee0ed4'
down_revision = 'b106403bf674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
   
    
    op.create_table('eds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eds_type', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=80), nullable=True),
    sa.Column('authorized_by', sa.String(length=80), nullable=True),
    sa.Column('planner', sa.String(length=80), nullable=True),
    sa.Column('team', sa.String(length=80), nullable=True),
    sa.Column('contributors', sa.String(length=80), nullable=True),
    sa.Column('oracle', sa.String(length=80), nullable=True),
    sa.Column('rpats', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('release_date', sa.String(length=80), nullable=True),
    sa.Column('target_date', sa.String(length=80), nullable=True),
    sa.Column('revision', sa.String(length=80), nullable=True),
    sa.Column('revision_date', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('TPIA_AEupdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=80), nullable=True),
    sa.Column('request_code', sa.String(length=80), nullable=True),
    sa.Column('overview', sa.String(length=80), nullable=True),
    sa.Column('cili', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('regions', sa.String(length=80), nullable=True),
    sa.Column('site', sa.String(length=80), nullable=True),
    sa.Column('router', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('aeid', sa.String(length=80), nullable=True),
    sa.Column('port', sa.String(length=80), nullable=True),
    sa.Column('port_new', sa.String(length=80), nullable=True),
    sa.Column('old_mb', sa.String(length=80), nullable=True),
    sa.Column('new_mb', sa.String(length=80), nullable=True),
    sa.Column('new_gig', sa.String(length=80), nullable=True),
    sa.Column('phys_links', sa.String(length=80), nullable=True),
    sa.Column('dependancy', sa.String(length=80), nullable=True),

    # sa.Column('', sa.Integer(), nullable=True),
    
    sa.Column('eds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eds_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('eds')
    op.drop_table('TPIA_AEupdate')
    # ### end Alembic commands ###
