"""first migration

Revision ID: b106403bf674
Revises: 
Create Date: 2021-06-17 11:57:01.811619

"""
from alembic import op
import sqlalchemy as sa
from myproject import db


# revision identifiers, used by Alembic.
revision = 'b106403bf674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eds_type', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('authorized_by', sa.String(length=50), nullable=True),
    sa.Column('planner', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('contributors', sa.String(length=50), nullable=True),
    sa.Column('oracle', sa.String(length=50), nullable=True),
    sa.Column('rpats', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('revision_date', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'],['users.id'],),
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('eds')
    # ### end Alembic commands ###
